name: CatFish
version: 0.0.0.10
main: org.CatAndDomi.CatFish
author: [ BabyNako and Dominicus ]
api-version: 1.20
description: 도미켓
libraries:
  - io.github.rysefoxx.inventory:RyseInventory-Plugin:1.5.7